# Generated by Django 6.0 on 2025-12-29 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la consola (único)', max_length=50, unique=True)),
                ('fabricante', models.CharField(help_text='Fabricante de la consola (Nintendo, Sega, Sony...)', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Consolas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la desarrolladora (único)', max_length=100, unique=True)),
                ('pais', models.CharField(help_text='País de origen de la desarrolladora', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del juego', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del juego')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del juego', max_digits=6)),
                ('anyo', models.IntegerField(help_text='Año de lanzamiento del juego')),
                ('estado', models.CharField(choices=[('N', 'Nuevo'), ('U', 'Usado'), ('S', 'Sellado')], help_text='Estado del juego (Nuevo/Usado/Sellado)', max_length=1)),
                ('disponible', models.BooleanField(default=True, help_text='Indica si el juego está disponible para venta')),
                ('fecha_salida', models.DateField(help_text='Fecha de salida original del juego')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro del juego')),
                ('consola', models.ForeignKey(help_text='Consola a la que pertenece el juego', null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.consola')),
                ('desarrolladora', models.ForeignKey(help_text='Desarrolladora del juego', on_delete=django.db.models.deletion.CASCADE, to='juegos.desarrolladora')),
            ],
            options={
                'verbose_name': 'Juego',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del pedido')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total del pedido', max_digits=8)),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza el pedido', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del usuario (opcional)', null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto (opcional)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del perfil')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del perfil')),
                ('usuario', models.OneToOneField(help_text='Usuario asociado al perfil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Usuario',
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de unidades del juego')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento del pedido', max_digits=6)),
                ('juego', models.ForeignKey(help_text='Juego en la línea del pedido', on_delete=django.db.models.deletion.CASCADE, to='juegos.juego')),
                ('pedido', models.ForeignKey(help_text='Pedido asociado', on_delete=django.db.models.deletion.CASCADE, to='juegos.pedido')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pedido', 'juego'), name='unique_juego_pedido')],
            },
        ),
    ]
